id: P000732
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:39:32.461363
source_metadata:
  id: bdr:W1AC337
  title: གསེར་ཡུལ་གནས་མཆོག་
  author: ''
  volumes:
    b10cae0f9635498ab13767de63900f9c:
      image_group_id: I2PD18903
      title: ''
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
