id: I09426C6C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:18:21+00:00'
last_modified: '2022-06-07T13:35:21.706067+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC337
  title: གསེར་ཡུལ་གནས་མཆོག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    3AF5:
      image_group_id: I2PD18903
      title: ''
      total_pages: 152
      order: 1
      base_file: 3AF5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
